import { Building2, Check, Landmark, ShieldCheck, Smartphone, UsersRound } from 'lucide-react';
import { BusinessModelRoutes } from './business-model-routes';

function RouteCard({ label, title, status, body, points, tone }: { label: string; title: string; status: string; body: string; points: string[]; tone: 'teal' | 'amber' | 'lavender' }) {
  const styles = tone === 'teal' ? 'bg-[#edf8f7] text-[#075e5b]' : tone === 'amber' ? 'bg-[#fff6ef] text-[#9a4d21]' : 'bg-[#f4f1fa] text-[#65558a]';
  return <article className="rounded-3xl border border-stone-200 bg-white p-6 sm:p-7"><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#007f7a]">{label}</p><span className={`rounded-full px-3 py-1 text-[10px] font-semibold uppercase tracking-wide ${styles}`}>{status}</span></div><h2 className="mt-5 text-2xl font-semibold tracking-[-.03em]">{title}</h2><p className="mt-3 text-sm leading-7 text-stone-600">{body}</p><ul className="mt-6 space-y-3 text-sm text-stone-600">{points.map(point=><li key={point} className="flex gap-3"><Check className="mt-0.5 h-4 w-4 shrink-0 text-[#007f7a]"/>{point}</li>)}</ul></article>;
}

export function BusinessModelSection() {
  return <>
    <header className="max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#007f7a]">Business model</p><h1 className="balanced mt-4 text-4xl font-semibold tracking-[-.05em] sm:text-5xl">Two active pathways to bring Tellie to entire communities.</h1><p className="mt-5 text-lg leading-8 text-stone-600">Residential providers fund Tellie as a resident, staff and family ecosystem. Councils sponsor Tellie as a place-based connection program. Both begin with a measurable pilot and create a clear path to recurring deployment.</p></header>

    <div className="mt-10 grid gap-4 lg:grid-cols-3">
      <RouteCard label="B2B2C · Primary entry" title="Residential providers" status="Pilot-led · now" tone="teal" body="The provider is the initial economic buyer and distribution partner. Residents use Tellie; staff and families receive permissioned value around that experience." points={['Concentrated, lower-cost distribution','Per-resident recurring revenue','Facility and family add-ons','Path from pilot to multi-site rollout']} />
      <RouteCard label="B2G · Parallel channel" title="Council programs" status="Pilot-led · now" tone="lavender" body="Councils can fund place-based access as a public-benefit initiative, with community-level insight and formal evaluation." points={['Program or participant pricing','Community recruitment and activation','Aggregated council dashboard','Potential multi-year program renewal']} />
      <RouteCard label="B2C · Future expansion" title="Families purchasing directly" status="Later" tone="amber" body="Families may eventually purchase Tellie for an older relative. This is a high-volume channel requiring proven retention, scalable support and efficient acquisition." points={['Launch after B2B validation','Distinct consumer bundle and pricing','No partner undercutting','Higher-volume marketing model']} />
    </div>

    <BusinessModelRoutes />

    <section className="mt-12 grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className="rounded-3xl bg-[#283c3a] p-7 text-white sm:p-9"><ShieldCheck className="h-7 w-7 text-[#8ed3cf]"/><p className="mt-6 text-xs font-semibold uppercase tracking-[.14em] text-[#8ed3cf]">Partner advantage</p><h2 className="mt-3 text-2xl font-semibold">Tellie helps providers offer something families can see and value.</h2><p className="mt-4 text-sm leading-7 text-stone-300">Residential partners receive the strongest package: resident access, facility insight and an optional family experience they can include or offer as a premium service.</p></div><div className="grid gap-4 sm:grid-cols-2">{[[Building2,'Provider','Pays for resident access, facility intelligence and optional family enablement.'],[Smartphone,'Older adult','Uses the companion and receives the primary connection benefit.'],[UsersRound,'Family','Receives permissioned reassurance and connection prompts through the provider.'],[Landmark,'Council','Funds community access and receives aggregated public-benefit insight.']].map(([Icon,title,body])=>{const C=Icon as typeof Building2;return <article key={title as string} className="rounded-2xl border border-stone-200 bg-white p-5"><C className="h-5 w-5 text-[#007f7a]"/><h3 className="mt-4 font-semibold">{title as string}</h3><p className="mt-2 text-xs leading-5 text-stone-600">{body as string}</p></article>})}</div></section>

    <div className="mt-12 rounded-3xl border border-stone-200 bg-white p-6 sm:p-8"><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#007f7a]">Commercial sequence</p><div className="mt-6 grid gap-3 md:grid-cols-5">{[['01','Validate','Residential pilots'],['02','Convert','Paid facility rollout'],['03','Expand','Dashboard + family add-ons'],['04','Scale','Multi-site providers'],['05','Open later','Channel-safe B2C']].map(([number,title,body])=><div key={number} className="rounded-2xl bg-[#f7f7f5] p-4"><span className="text-xs font-semibold text-[#007f7a]">{number}</span><p className="mt-3 text-sm font-semibold">{title}</p><p className="mt-1 text-xs leading-5 text-stone-500">{body}</p></div>)}</div></div>

    <div className="mt-8 rounded-2xl bg-[#fff6ef] p-5 text-xs leading-6 text-stone-600"><strong className="text-stone-800">Pricing remains a validation question.</strong> Examples such as a provider paying A$20 and reselling family access at A$50 illustrate the model, not a committed price. Pilots should test willingness to pay, packaging, margin sharing, care-package eligibility and contract structure before final pricing is published.</div>
  </>;
}
