import { Bot, Check, CircleMinus, HeartPulse, Phone, ShieldCheck, Smartphone, Watch } from 'lucide-react';

const competitors = [
  { name:'Tellie', market:'Australia', category:'Senior connection platform', form:'Mobile app + familiar phone prototype', audience:'Older adults, providers, families, councils', value:'Sustained conversation that becomes permissioned support insight', family:'Family Connect app', provider:'Residential + council dashboards', price:'Working hypothesis: A$20/resident + A$150/facility dashboard + A$25/enabled family monthly', tone:'tellie' },
  { name:'CareCob', market:'Australia', category:'Closest direct competitor', form:'AI calls to an existing landline or mobile', audience:'Older adults, families and care facilities', value:'Daily companionship, wellness checks, reminders and alerts', family:'SMS summaries + wellness dashboard', provider:'Enterprise admin and caregiver dashboards with analytics', price:'From A$59/month individual; A$149 family; enterprise quote', tone:'direct' },
  { name:'Nearness', market:'Australia', category:'Closest direct competitor', form:'AI calls to an existing landline or mobile', audience:'Older adults, families and aged-care organisations', value:'Scheduled personalised companion calls, memory and reminders', family:'Call summaries, wellbeing notes, dashboard and distress alerts', provider:'Bulk and white-label provider arrangements', price:'A$19–A$79/month; provider pricing by quote', tone:'direct' },
  { name:'Chatter Buddy', market:'Australia', category:'Direct app competitor', form:'iOS and Android conversational app', audience:'Seniors, families and care providers', value:'AI conversation, entertainment and gentle reminders', family:'Family positioning; detailed insight layer not publicly evidenced', provider:'Enterprise plan offered; analytics not publicly evidenced', price:'Free; A$29–A$79/month listed plans; enterprise quote', tone:'direct' },
  { name:'Ato', market:'United States', category:'Direct device competitor', form:'Screen-free dedicated voice device', audience:'Older adults and family caregivers', value:'Proactive companionship, information, reminders and engagement', family:'Care Hub with activity, messages, reminders and reports', provider:'No provider or council dashboard publicly evidenced', price:'US$179 device + US$29/month after first month', tone:'direct' },
  { name:'ElliQ', market:'United States', category:'Direct device competitor', form:'Dedicated companion device with screen', audience:'Adults 60+ living or spending substantial time alone', value:'Proactive companionship, wellness, games and connection', family:'Circle of Care and caregiver connection', provider:'Healthcare and funded-program partnerships', price:'US$249 initiation + approximately US$39.99–US$59.99/month', tone:'direct' },
  { name:'Resparke', market:'Australia', category:'Provider engagement platform', form:'Purpose-built hardware + content platform', audience:'Residential aged-care teams and residents', value:'Personalised music, video, games and dementia engagement', family:'Family connection and personalised content', provider:'Resident profiles, content and person-centred engagement workflows', price:'Quote only', tone:'adjacent' },
  { name:'Qolo', market:'Australia', category:'Resident experience platform', form:'Accessible resident app', audience:'Residents, families, carers and administrators', value:'Entertainment, communication, planner, translation and cue cards', family:'Gallery, social feed, messaging and one-touch video calls', provider:'Digital forms and care-administration tools', price:'Not publicly listed', tone:'adjacent' },
  { name:'CareApp', market:'Australia', category:'Care engagement platform', form:'Provider, family and recipient apps', audience:'Aged-care and disability providers', value:'Family updates, wellbeing checks and evidence of delivered care', family:'Visibility into care and everyday moments', provider:'Time-stamped evidence, compliance and add-on service commerce', price:'Quote only', tone:'adjacent' },
  { name:'LifeLoop', market:'United States', category:'Senior-living platform', form:'Resident, staff and family portals', audience:'Senior-living operators, residents and families', value:'Activities, communication, transport and resident engagement', family:'Feeds, photos, messages, milestones and requests', provider:'Engagement operations and performance insights', price:'Quote only', tone:'adjacent' },
  { name:'K4Connect', market:'United States', category:'Senior-living platform', form:'Apps + smart-home integrations', audience:'Senior-living operators, residents and families', value:'Community information, engagement, communications and home control', family:'Video, messaging, photo sharing and community updates', provider:'FusionOS integrations and operational data', price:'Quote only', tone:'adjacent' },
  { name:'Rendever', market:'United States', category:'Immersive engagement', form:'VR headsets + staff tablet + web platform', audience:'Senior-living communities', value:'Shared virtual travel, events, games and reminiscence', family:'Family portal and custom reminiscence journeys', provider:'Resident profiles; analytics in upper tier', price:'Hardware setup + recurring subscription; quote only', tone:'adjacent' },
  { name:'Replika', market:'Global', category:'AI companion substitute', form:'Consumer mobile and web app', audience:'General consumers', value:'Customisable AI friendship and emotional conversation', family:'No elder-family support experience evidenced', provider:'No residential or council intelligence layer evidenced', price:'Free + paid subscriptions; regional pricing varies', tone:'substitute' },
  { name:'ChatGPT / Gemini / Siri', market:'Global', category:'General AI substitute', form:'Apps and device-integrated assistants', audience:'General consumers', value:'Information, productivity, voice assistance and search', family:'General sharing—not elder-family support', provider:'General tools—not resident insight products', price:'Free and paid options; hardware may be required', tone:'substitute' },
  { name:'Apple Watch / fall detection', market:'Australia + US', category:'Safety alternative', form:'Wearable hardware', audience:'General consumers, including older adults', value:'Health, activity, emergency SOS and hard-fall detection', family:'Emergency contacts and location notifications', provider:'Health ecosystem—not conversation-derived insight', price:'Apple Watch SE from A$399; connectivity may cost extra', tone:'adjacent' },
] as const;

const toneStyle = (tone: string) => tone === 'tellie' ? 'bg-[#dff1ef] text-[#075e5b]' : tone === 'direct' ? 'bg-[#fff0e5] text-[#9a4d21]' : tone === 'substitute' ? 'bg-[#f0eef7] text-[#65558a]' : 'bg-stone-100 text-stone-600';

export function CompetitorSection() {
  return <>
    <header className="max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#007f7a]">Competition</p><h1 className="balanced mt-4 text-4xl font-semibold tracking-[-.05em] sm:text-5xl">Tellie turns conversation into a connection advantage.</h1><p className="mt-5 text-lg leading-8 text-stone-600">Most alternatives serve one audience or one moment. Tellie connects the whole support circle: an engaging companion for the older adult, timely insight for families and providers, and community-level intelligence for councils.</p></header>

    <div className="mt-10 grid gap-4 lg:grid-cols-4">
      {[[Phone,'A complete connection loop','Tellie unites companionship, family connection, provider insight and council intelligence in one ecosystem.'],[Bot,'Built for older adults','A familiar phone-call experience removes the complexity of general AI and feature-heavy interfaces.'],[HeartPulse,'Insight that prompts action','Conversation reveals interests, mood and moments when better-timed human support can matter most.'],[Watch,'One relationship, multiple returns','The same engagement creates resident value, staff context, family reassurance and measurable program insight.']].map(([Icon,title,body])=>{const C=Icon as typeof Phone;return <article key={title as string} className="rounded-2xl border border-stone-200 bg-white p-6"><C className="h-5 w-5 text-[#007f7a]"/><h2 className="mt-4 font-semibold">{title as string}</h2><p className="mt-2 text-sm leading-6 text-stone-600">{body as string}</p></article>})}
    </div>

    <section className="mt-12 overflow-hidden rounded-[28px] border border-stone-200 bg-white">
      <div className="border-b border-stone-200 p-6 sm:p-8"><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#007f7a]">Competitive matrix</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.04em]">Different products solve different parts of the problem.</h2></div>
      <div className="overflow-x-auto"><table className="min-w-[1280px] w-full border-collapse text-left text-xs"><thead className="bg-[#283c3a] text-white"><tr>{['Product','Market','Category','Form factor','Primary audience','Core value','Family layer','Institutional insight','Public pricing'].map(label=><th key={label} className="px-4 py-4 font-semibold">{label}</th>)}</tr></thead><tbody>{competitors.map((item,index)=><tr key={item.name} className={`${index%2 ? 'bg-stone-50' : 'bg-white'} align-top`}><td className="border-b border-stone-200 px-4 py-5"><strong className="text-sm text-stone-900">{item.name}</strong>{item.name==='Tellie'&&<span className="ml-2 rounded-full bg-[#007f7a] px-2 py-1 text-[9px] font-semibold uppercase text-white">Us</span>}</td><td className="border-b border-stone-200 px-4 py-5 font-medium text-stone-700">{item.market}</td><td className="border-b border-stone-200 px-4 py-5"><span className={`rounded-full px-2.5 py-1 text-[9px] font-semibold uppercase tracking-wide ${toneStyle(item.tone)}`}>{item.category}</span></td><td className="max-w-44 border-b border-stone-200 px-4 py-5 leading-5 text-stone-600">{item.form}</td><td className="max-w-48 border-b border-stone-200 px-4 py-5 leading-5 text-stone-600">{item.audience}</td><td className="max-w-56 border-b border-stone-200 px-4 py-5 leading-5 text-stone-600">{item.value}</td><td className="max-w-52 border-b border-stone-200 px-4 py-5 leading-5 text-stone-600">{item.family}</td><td className="max-w-56 border-b border-stone-200 px-4 py-5 leading-5 text-stone-600">{item.provider}</td><td className="max-w-60 border-b border-stone-200 px-4 py-5 leading-5 text-stone-600">{item.price}</td></tr>)}</tbody></table></div>
    </section>

    <section className="mt-12 grid gap-6 lg:grid-cols-[.85fr_1.15fr]">
      <div className="rounded-3xl bg-gradient-to-br from-[#edf8f7] to-white p-7 ring-1 ring-[#cfe7e5] sm:p-9"><Smartphone className="h-7 w-7 text-[#007f7a]"/><p className="mt-6 text-xs font-semibold uppercase tracking-[.14em] text-[#007f7a]">Tellie’s design thesis</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.04em] text-[#283c3a]">Meet older adults where they are technologically.</h2><p className="mt-4 text-sm leading-7 text-stone-600">Tellie begins with something older adults grew up with and already know how to use confidently: a phone call. Both the mobile experience and familiar-phone prototype are designed around that behaviour, so the technology adapts to the person—not the other way around.</p></div>
      <div className="grid gap-4 sm:grid-cols-2">{[[Check,'Familiar interaction','Pick up, answer and speak—rather than navigate a new robot or complex interface.'],[Check,'Sustained conversation','Value increases with meaningful engagement, continuity and permissioned memory.'],[Check,'Three-sided value','One conversation can benefit the resident, provider and family in different ways.'],[Check,'Institutional distribution','Residential and council dashboards support models beyond direct consumer subscription.'],[CircleMinus,'Not feature maximalism','Tellie does not need to outperform general AI on every task; it must be easier and more relevant.'],[ShieldCheck,'Permissioned insight','The differentiation depends on trustworthy extraction and sharing—not surveillance.']].map(([Icon,title,body])=>{const C=Icon as typeof Check;return <article key={title as string} className="rounded-2xl border border-stone-200 bg-white p-5"><C className="h-5 w-5 text-[#007f7a]"/><h3 className="mt-4 font-semibold">{title as string}</h3><p className="mt-2 text-xs leading-5 text-stone-600">{body as string}</p></article>})}</div>
    </section>

    <section className="mt-12 rounded-[28px] border border-stone-200 bg-white p-6 sm:p-9"><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#007f7a]">Why Tellie is positioned to win</p><div className="mt-6 grid gap-4 md:grid-cols-3"><article className="rounded-2xl bg-[#fff6ef] p-5"><h3 className="font-semibold">Designed for conversation depth</h3><p className="mt-2 text-sm leading-6 text-stone-600">Sustained, personalised conversation builds continuity, engagement and a richer understanding of what matters to each person.</p></article><article className="rounded-2xl bg-[#f4f1fa] p-5"><h3 className="font-semibold">Familiar from the first conversation</h3><p className="mt-2 text-sm leading-6 text-stone-600">Tellie is built around something older adults already recognise and confidently know how to do: answer a phone call and talk.</p></article><article className="rounded-2xl bg-[#edf8f7] p-5"><h3 className="font-semibold">Commercial value compounds</h3><p className="mt-2 text-sm leading-6 text-stone-600">Companion access opens the account; provider intelligence and Family Connect expand value and recurring revenue.</p></article></div></section>

    <div className="mt-10 border-t border-stone-200 pt-6"><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#007f7a]">Primary product sources</p><div className="mt-4 flex flex-wrap gap-x-5 gap-y-3 text-xs font-semibold">{[
      ['CareCob product and pricing','https://www.carecob.com.au/pricing/'],['Nearness product and pricing','https://nearness.com.au/nearness-pricing.html'],['Chatter Buddy pricing','https://chatterbuddy.com.au/our-pricing-plans/'],['Resparke','https://resparke.com/'],['Qolo','https://www.qolo.com.au/'],['CareApp','https://careapp.com.au/'],['Ato product and pricing','https://heyato.ai/'],['ElliQ features and pricing','https://elliq.com/pages/faqs'],['LifeLoop','https://lifeloop.com/engagement/engagement-products/connection-portal'],['K4Connect','https://www.k4connect.com/plus/'],['Rendever','https://www.rendever.com/faqs'],['Replika subscriptions','https://help.replika.com/hc/en-us/articles/39551043419149-Choosing-a-Subscription'],['ChatGPT pricing','https://openai.com/chatgpt/pricing'],['Apple Watch pricing','https://www.apple.com/au/shop/buy-watch/apple-watch']
    ].map(([label,url])=><a key={label} href={url} target="_blank" rel="noreferrer" className="text-[#007f7a] underline decoration-[#9ccfcb] underline-offset-4 hover:text-[#075e5b]">{label} ↗</a>)}</div></div>
  </>;
}
