import { Accessibility, BellRing, BookOpen, CalendarCheck, ChevronRight, CircleOff, Gamepad2, Globe2, Heart, HeartPulse, Languages, MessageCircle, Mic2, Search, ShieldCheck, Smartphone, Sparkles, Stethoscope, TriangleAlert, Users, Watch } from 'lucide-react';
import { ProductDashboards } from './product-dashboards';
import { HardwarePrototypeSection } from './hardware-prototype-section';

type Card = { title: string; body: string; eyebrow?: string };

function Heading({ eyebrow, title, intro }: { eyebrow: string; title: string; intro: string }) {
  const intentionalMessaging: Record<string, [string, string]> = {
    Market: ['4.7 million older Australians. One concentrated path to reach them.', 'Tellie begins in residential care, where a single provider relationship can reach an entire community, demonstrate outcomes and expand across sites.'],
    Product: ['A companion for the elder. A connection platform for everyone around them.', 'Tellie makes conversation feel as familiar as a phone call, then turns permissioned signals into timely, useful support for families, residential providers and councils.'],
  };
  const [resolvedTitle, resolvedIntro] = intentionalMessaging[eyebrow] ?? [title, intro];
  return <header className="max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#007f7a]">{eyebrow}</p><h1 className="balanced mt-4 text-4xl font-semibold tracking-[-.05em] sm:text-5xl">{resolvedTitle}</h1><p className="mt-5 text-lg leading-8 text-stone-600">{resolvedIntro}</p></header>;
}

function Cards({ cards }: { cards: Card[] }) {
  return <div className="mt-10 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{cards.map(card => <article key={card.title} className="rounded-2xl border border-stone-200 bg-white p-6"><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#007f7a]">{card.eyebrow}</p><h2 className="mt-3 text-lg font-semibold tracking-[-.02em]">{card.title}</h2><p className="mt-2 text-sm leading-6 text-stone-600">{card.body}</p></article>)}</div>;
}

function Detail({ title, children, open = false, fullWidth = false }: { title: string; children: React.ReactNode; open?: boolean; fullWidth?: boolean }) {
  return <details open={open} className="group border-b border-stone-200 py-1"><summary className="focus-ring flex cursor-pointer list-none items-center justify-between gap-4 rounded-xl py-5 text-base font-semibold"><span>{title}</span><span className="text-xl font-light text-stone-500 transition group-open:rotate-45">+</span></summary><div className={`${fullWidth ? 'w-full max-w-none' : 'max-w-5xl'} pb-6 text-sm leading-7 text-stone-600`}>{children}</div></details>;
}

export function ProblemSection() {
  return <>
    <Heading eyebrow="The problem we solve" title="Older adults spend too much time alone." intro="Families cannot always be there. Care happens at scheduled touchpoints. The hours in between can be long, lonely and isolating." />
    <div className="mt-10 grid gap-4 lg:grid-cols-[1.25fr_.75fr]">
      <div className="rounded-3xl border border-[#cfe7e5] bg-gradient-to-br from-[#edf8f7] to-white p-7 sm:p-10"><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#007f7a]">Why this matters</p><p className="balanced mt-4 text-2xl font-semibold tracking-[-.03em] text-[#283c3a] sm:text-4xl">Loneliness affects health, wellbeing and quality of life.</p></div>
      <div className="rounded-3xl border border-stone-200 bg-white p-7 sm:p-10"><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#007f7a]">Why now</p><p className="mt-4 text-lg font-semibold">More people are living longer while families and care systems are stretched.</p></div>
    </div>
    <Cards cards={[
      { eyebrow:'The gap', title:'Human support is not continuous', body:'Family visits and care touchpoints matter, but many hours remain unfilled.' },
      { eyebrow:'The amplifier', title:'Technology can deepen isolation', body:'When communication and services become harder to access, disconnection grows.' },
      { eyebrow:'The hidden signal', title:'Loneliness is difficult to see', body:'The people around an elder may not know when connection is needed most.' },
    ]} />
    <div className="mt-10 overflow-hidden rounded-3xl border border-[#cfe7e5] bg-gradient-to-br from-[#edf8f7] via-white to-[#fff6ef] p-7 sm:p-10">
      <div className="flex items-start gap-4"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-full bg-white shadow-sm"><Heart className="h-5 w-5 fill-[#e98e85] text-[#e98e85]" /></span><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#007f7a]">Tellie’s point of view</p><blockquote className="balanced mt-4 max-w-4xl text-2xl font-semibold leading-tight tracking-[-.03em] text-[#283c3a] sm:text-4xl">Connection begins with a conversation.</blockquote><p className="mt-5 max-w-3xl text-sm leading-7 text-stone-600">Conversation helps Tellie understand what matters, recognise change and guide families, care providers and communities toward better support.</p></div></div>
    </div>
    <div className="mt-10">
      <Detail title="Why loneliness is growing" open>
        <p className="max-w-3xl">The risk is growing in scale as Australia ages. Longer life is positive—but later life can bring retirement, bereavement, reduced mobility, ill health and dispersed families, all of which can narrow everyday connection.</p>
        <div className="mt-5 grid gap-3 md:grid-cols-3">
          <div className="rounded-2xl bg-[#edf8f7] p-5"><p className="text-2xl font-semibold tracking-[-.04em] text-[#075e5b]">23.4%</p><p className="mt-2 font-semibold text-stone-800">An older population</p><p className="mt-1 text-xs leading-5">Australians aged 65+ are projected to reach 23.4% of the population by 2062–63. The 85+ population will more than triple.</p></div>
          <div className="rounded-2xl bg-[#fff6ef] p-5"><p className="text-2xl font-semibold tracking-[-.04em] text-[#9a4d21]">Longer lives</p><p className="mt-2 font-semibold text-stone-800">More vulnerable transitions</p><p className="mt-1 text-xs leading-5">Australians are living longer, while expected years lived with ill health have also increased—adding periods when connection can become harder to maintain.</p></div>
          <div className="rounded-2xl bg-[#f4f1fa] p-5"><p className="text-2xl font-semibold tracking-[-.04em] text-[#65558a]">Public health</p><p className="mt-2 font-semibold text-stone-800">Not simply a social discomfort</p><p className="mt-1 text-xs leading-5">Loneliness and social isolation are associated with poorer mental and physical health, dementia, cardiovascular disease and premature death.</p></div>
        </div>
        <p className="mt-5 rounded-xl border border-stone-200 bg-white px-4 py-3 text-xs leading-5"><strong className="text-stone-800">Two related problems:</strong> loneliness means feeling alone—even when other people are nearby. Social isolation means having very little contact with others—even if the person does not feel lonely. Tellie is primarily designed to address the feeling of loneliness, while helping create more opportunities for human connection.</p>
        <div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-xs font-semibold">
          <a className="text-[#007f7a] underline decoration-[#9ccfcb] underline-offset-4 hover:text-[#075e5b]" href="https://treasury.gov.au/publication/2023-intergenerational-report" target="_blank" rel="noreferrer">Treasury · population ageing ↗</a>
          <a className="text-[#007f7a] underline decoration-[#9ccfcb] underline-offset-4 hover:text-[#075e5b]" href="https://www.aihw.gov.au/reports/australias-health/health-of-older-people" target="_blank" rel="noreferrer">AIHW · health of older people ↗</a>
          <a className="text-[#007f7a] underline decoration-[#9ccfcb] underline-offset-4 hover:text-[#075e5b]" href="https://www.who.int/groups/commission-on-social-connection" target="_blank" rel="noreferrer">WHO · social connection ↗</a>
          <a className="text-[#007f7a] underline decoration-[#9ccfcb] underline-offset-4 hover:text-[#075e5b]" href="https://www.aihw.gov.au/mental-health/topic-areas/health-wellbeing/social-isolation-and-loneliness" target="_blank" rel="noreferrer">AIHW · loneliness and isolation ↗</a>
        </div>
      </Detail>
      <Detail title="How loneliness affects health">
        <p className="max-w-3xl">Loneliness is more than an unpleasant feeling. Persistent loneliness and social disconnection are associated with serious physical, cognitive and mental-health consequences—which is why the World Health Organization treats social connection as a public-health priority.</p>
        <div className="mt-5 grid gap-3 md:grid-cols-3">
          <div className="rounded-2xl bg-[#fff6ef] p-5"><HeartPulse className="h-5 w-5 text-[#a8542c]"/><p className="mt-4 font-semibold text-stone-800">Physical health</p><p className="mt-2 text-xs leading-5">Associated with increased risk of heart disease, stroke, high blood pressure, type 2 diabetes and premature death.</p></div>
          <div className="rounded-2xl bg-[#f4f1fa] p-5"><Sparkles className="h-5 w-5 text-[#65558a]"/><p className="mt-4 font-semibold text-stone-800">Brain and cognition</p><p className="mt-2 text-xs leading-5">Chronic loneliness and social isolation are associated with cognitive decline and dementia risk.</p></div>
          <div className="rounded-2xl bg-[#edf8f7] p-5"><Heart className="h-5 w-5 text-[#007f7a]"/><p className="mt-4 font-semibold text-stone-800">Mental health</p><p className="mt-2 text-xs leading-5">Associated with depression, anxiety, psychological distress and increased risk of self-harm or suicide.</p></div>
        </div>
        <p className="mt-5 text-xs leading-5"><strong className="text-stone-800">Evidence note:</strong> these are population-level associations. Loneliness does not mean an individual will develop any particular illness, and Tellie does not diagnose, treat or prevent disease.</p>
        <div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-xs font-semibold">
          <a className="text-[#007f7a] underline decoration-[#9ccfcb] underline-offset-4 hover:text-[#075e5b]" href="https://www.who.int/publications/i/item/978240112360" target="_blank" rel="noreferrer">WHO · Commission on Social Connection report ↗</a>
          <a className="text-[#007f7a] underline decoration-[#9ccfcb] underline-offset-4 hover:text-[#075e5b]" href="https://www.who.int/news-room/questions-and-answers/item/social-connection" target="_blank" rel="noreferrer">WHO · health impacts of social connection ↗</a>
          <a className="text-[#007f7a] underline decoration-[#9ccfcb] underline-offset-4 hover:text-[#075e5b]" href="https://www.aihw.gov.au/mental-health/topic-areas/health-wellbeing/social-isolation-and-loneliness" target="_blank" rel="noreferrer">AIHW · Australian evidence ↗</a>
        </div>
      </Detail>
      <Detail title="How digital exclusion relates">
        <p className="max-w-3xl">Digital exclusion is not the core problem Tellie solves. It is an amplifier: as communication, services and community participation move online, people who cannot use them confidently lose pathways to real-world connection.</p>
        <div className="mt-5 grid gap-3 md:grid-cols-3">
          <div className="rounded-2xl border border-stone-200 bg-white p-5"><p className="text-2xl font-semibold tracking-[-.04em] text-[#075e5b]">25 points</p><p className="mt-2 font-semibold text-stone-800">Below the national average</p><p className="mt-1 text-xs leading-5">Australians aged 75+ recorded the lowest digital-inclusion score: 49, compared with a national average of 74.</p></div>
          <div className="rounded-2xl border border-stone-200 bg-white p-5"><p className="text-2xl font-semibold tracking-[-.04em] text-[#075e5b]">37%</p><p className="mt-2 font-semibold text-stone-800">Need help keeping up</p><p className="mt-1 text-xs leading-5">More than one in three Australians aged 65+ reported needing help to keep pace with changes in technology.</p></div>
          <div className="rounded-2xl border border-stone-200 bg-white p-5"><p className="text-2xl font-semibold tracking-[-.04em] text-[#075e5b]">1 in 4</p><p className="mt-2 font-semibold text-stone-800">Feel anxious online</p><p className="mt-1 text-xs leading-5">One in four older Australians felt anxious when they could not complete an online task without help.</p></div>
        </div>
        <p className="mt-5 text-xs leading-5">Tellie’s opportunity is to make digital capability feel like a familiar conversation—not another interface an older person must learn.</p>
        <a className="mt-4 inline-flex text-xs font-semibold text-[#007f7a] underline decoration-[#9ccfcb] underline-offset-4 hover:text-[#075e5b]" href="https://www.infrastructure.gov.au/sites/default/files/documents/digital-exclusion-in-australia-report.pdf" target="_blank" rel="noreferrer">Australian Government · Digital Exclusion in Australia ↗</a>
      </Detail>
      <Detail title="How Tellie will demonstrate impact"><p>Structured pilots measure meaningful repeat conversation, perceived connection and better-timed human support—building the evidence partners need for wider deployment.</p></Detail>
    </div>
  </>;
}

export function MarketSection() {
  return <>
    <Heading eyebrow="Market" title="4.7 million older Australians. A focused residential-care entry." intro="Tellie addresses a population-wide need, beginning where distribution is concentrated and the need for connection is especially visible." />
    <section className="mt-10 rounded-[28px] border border-stone-200 bg-white p-6 sm:p-9">
      <p className="text-xs font-semibold uppercase tracking-[.16em] text-[#007f7a]">From population to initial beachhead</p>
      <div className="mt-6 grid gap-3 lg:grid-cols-4">
        <article className="rounded-2xl bg-[#edf8f7] p-6"><p className="text-xs font-semibold text-[#007f7a]">01 · Australia</p><p className="mt-4 text-4xl font-semibold tracking-[-.05em] text-[#075e5b]">4.7M</p><h2 className="mt-2 font-semibold">People aged 65+</h2><p className="mt-2 text-xs leading-5 text-stone-600">Around 17% of Australia’s 27.2 million residents at 30 June 2024.</p><p className="mt-3 text-[10px] font-semibold uppercase tracking-wide text-stone-400">ABS / AIHW · 2024 data</p></article>
        <article className="rounded-2xl bg-[#f4f1fa] p-6"><p className="text-xs font-semibold text-[#65558a]">02 · The need</p><p className="mt-4 text-4xl font-semibold tracking-[-.05em] text-[#65558a]">15%</p><h2 className="mt-2 font-semibold">Around 1 in 7 experience loneliness</h2><p className="mt-2 text-xs leading-5 text-stone-600">Among Australians aged 65+ in 2024—approximately 705,000 people when applied directionally to the rounded population count.</p><p className="mt-3 text-[10px] font-semibold uppercase tracking-wide text-stone-400">AIHW analysis of HILDA · 2024</p></article>
        <article className="rounded-2xl bg-[#fff6ef] p-6"><p className="text-xs font-semibold text-[#9a4d21]">03 · The entry market</p><p className="mt-4 text-4xl font-semibold tracking-[-.05em] text-[#9a4d21]">188K</p><h2 className="mt-2 font-semibold">Permanent-care residents</h2><p className="mt-2 text-xs leading-5 text-stone-600">Australians aged 65+ living in permanent residential aged care at 30 June 2024.</p><p className="mt-3 text-[10px] font-semibold uppercase tracking-wide text-stone-400">AIHW · 2024 data</p></article>
        <article className="rounded-2xl bg-[#eef5fa] p-6"><p className="text-xs font-semibold text-[#426b83]">04 · Concentrated need</p><p className="mt-4 text-4xl font-semibold tracking-[-.05em] text-[#426b83]">61%</p><h2 className="mt-2 font-semibold">Moderate loneliness in care homes</h2><p className="mt-2 text-xs leading-5 text-stone-600">Pooled international estimate cited by the Medical Journal of Australia in 2024; 35% experienced severe loneliness. Not an Australian national prevalence rate.</p><p className="mt-3 text-[10px] font-semibold uppercase tracking-wide text-stone-400">MJA review · 2024</p></article>
      </div>
      <p className="mt-5 text-xs leading-5 text-stone-500">The 705,000 figure is calculated as 15% of the rounded 4.7 million population and is therefore directional rather than an official published count. The national and care-home rates are not directly comparable: they use different populations, countries and measurement methods.</p>
      <div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-xs font-semibold"><a className="text-[#007f7a] underline decoration-[#9ccfcb] underline-offset-4" href="https://www.abs.gov.au/statistics/people/population/national-state-and-territory-population/jun-2024" target="_blank" rel="noreferrer">ABS · Australian population, June 2024 ↗</a><a className="text-[#007f7a] underline decoration-[#9ccfcb] underline-offset-4" href="https://www.aihw.gov.au/reports/australias-welfare/aged-care" target="_blank" rel="noreferrer">AIHW · older population and aged care ↗</a><a className="text-[#007f7a] underline decoration-[#9ccfcb] underline-offset-4" href="https://www.aihw.gov.au/mental-health/topic-areas/health-wellbeing/social-isolation-and-loneliness" target="_blank" rel="noreferrer">AIHW · loneliness by age, 2024 ↗</a><a className="text-[#007f7a] underline decoration-[#9ccfcb] underline-offset-4" href="https://www.mja.com.au/journal/2024/221/6/loneliness-epidemic-holistic-view-its-health-and-economic-implications-older-age" target="_blank" rel="noreferrer">Medical Journal of Australia · residential evidence ↗</a></div>
    </section>
    <div className="mt-8 grid gap-5 lg:grid-cols-3"><div className="rounded-3xl border border-stone-200 bg-white p-7"><p className="text-4xl font-semibold tracking-[-.05em]">A$240</p><p className="mt-2 text-sm font-semibold">Annual revenue per resident</p><p className="mt-3 text-xs leading-5 text-stone-500">Tellie pricing assumption: A$20 per resident per month. This is a company model, not an external statistic.</p></div><div className="rounded-3xl bg-[#eaf5f4] p-7"><p className="text-4xl font-semibold tracking-[-.05em] text-[#075e5b]">A$45.1M</p><p className="mt-2 text-sm font-semibold">Residential-care beachhead</p><p className="mt-3 text-xs leading-5 text-stone-600">188,000 permanent-care residents × A$240 annually = A$45.12 million. Directional market model, not a revenue forecast.</p></div><div className="rounded-3xl border border-stone-200 bg-white p-7"><p className="text-4xl font-semibold tracking-[-.05em]">4.0%</p><p className="mt-2 text-sm font-semibold">Of older Australians</p><p className="mt-3 text-xs leading-5 text-stone-500">188,000 ÷ 4.7 million. Permanent residential care is Tellie’s entry market—not the full population opportunity.</p></div></div>
    <section className="mt-12"><div className="max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#007f7a]">Why residential care first</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.04em]">A measurable segment with concentrated reach.</h2><p className="mt-3 text-sm leading-7 text-stone-600">Residential care is not Tellie’s entire market. It is a practical starting point where the buyer, user population and path to broader deployment are clearly identifiable.</p></div><div className="mt-7 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[
      ['Concentrated reach','One provider relationship can introduce Tellie to a substantial resident community.'],
      ['Identifiable buyer','The residential provider can evaluate, purchase and coordinate deployment.'],
      ['Visible need','Connection and person-centred engagement are recognised priorities within residential care.'],
      ['Expansion potential','A successful facility can create a pathway into additional sites within the provider group.'],
    ].map(([title,body],index) => <article key={title} className="rounded-2xl border border-stone-200 bg-white p-6"><span className="text-xs font-semibold text-[#007f7a]">0{index+1}</span><h3 className="mt-4 text-lg font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-stone-600">{body}</p></article>)}</div></section>
    <section className="mt-12"><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#007f7a]">Who this market involves</p><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[['User','Older adult','Receives companionship, continuity and a simpler path to human connection.'],['Initial buyer','Residential provider','Purchases and coordinates Tellie for participating residents.'],['Beneficiary','Family','Benefits from better-timed, permissioned connection with their loved one.'],['Parallel buyer','Council','Can fund community access through a separate public-benefit program.']].map(([label,title,body])=><article key={title} className="rounded-3xl border border-stone-200 bg-white p-6"><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#007f7a]">{label}</p><h2 className="mt-3 text-xl font-semibold">{title}</h2><p className="mt-3 text-sm leading-6 text-stone-600">{body}</p></article>)}</div></section>
    <div className="mt-10"><Detail title="Why now" open><p>The older population is growing, loneliness is recognised as a public-health and care challenge, families and care systems are under pressure, and person-centred care increasingly requires a better understanding of the individual. Conversational AI is also becoming accessible enough to deliver value through a familiar interaction.</p></Detail><Detail title="Beyond the initial market"><p>The broader opportunity includes older adults living independently, home and community care, family-supported access and selected international ageing markets. These segments are not included in the A$45.1 million residential-care calculation.</p></Detail><Detail title="Sources and assumptions"><p><strong>Official statistics:</strong> 27.2 million Australians, 4.7 million aged 65+, 15% loneliness prevalence and 188,000 permanent-care residents. <strong>Research estimate:</strong> 61% moderate loneliness in pooled international care-home research. <strong>Tellie calculation:</strong> approximately 705,000 older Australians experiencing loneliness and a 4.0% residential share. <strong>Company assumption:</strong> A$20 per resident monthly, producing a directional A$45.1 million residential opportunity—not a forecast.</p></Detail></div>
  </>;
}

function PhoneFrame() {
  return <div className="relative mx-auto w-[min(310px,82%)] rounded-[3.25rem] border-[9px] border-[#242424] bg-[#242424] p-[4px] shadow-[0_35px_70px_rgba(34,34,34,.22)]"><div className="absolute left-1/2 top-2 z-10 h-6 w-24 -translate-x-1/2 rounded-full bg-[#242424]"/><div className="overflow-hidden rounded-[2.55rem] bg-white"><img src="/tellie-call-screen.png" alt="Tellie mobile call screen" className="aspect-[9/19] h-auto w-full object-cover object-top" /></div></div>;
}

const features = [
  [Mic2,'Real-time voice','A natural conversation shaped around a familiar phone call.'],
  [MessageCircle,'Text conversation','A quiet, accessible alternative when voice is not practical.'],
  [Languages,'10+ languages','A multilingual experience, with quality validated language by language.'],
  [Sparkles,'Memory & personalisation','Preferences and meaningful context support continuity over time.'],
  [Gamepad2,'Cognitive games','Light activities designed to engage memory and stimulate the mind.'],
  [Search,'Light web search','Simple help finding useful, current information without navigating a browser.'],
  [BellRing,'Support-contact alerts','Signals can notify an agreed support contact when human connection may be needed.'],
  [CalendarCheck,'Reminders & calendar','Practical support for plans, routines, appointments and activities.'],
  [Globe2,'Community discovery','Relevant activities can connect conversation with real-world participation.'],
  [Accessibility,'Accessibility settings','Settings adapt the experience to individual visual, audio and interaction needs.'],
] as const;

export function ProductSection({ councilSrc, residentialSrc }: { councilSrc: string; residentialSrc: string }) {
  return <>
    <Heading eyebrow="Product" title="A companion shaped like a phone call." intro="Tellie gives older adults a warm, familiar way to talk, remember, discover and stay connected—while transforming relevant signals into useful support for families, residential providers and councils." />
    <div className="mt-10 grid gap-8 rounded-[28px] border border-stone-200 bg-white p-6 sm:p-10 lg:grid-cols-[.72fr_1.28fr] lg:items-center">
      <div className="grid min-h-[600px] place-items-center rounded-3xl bg-gradient-to-br from-[#dceeed] via-[#eef7f6] to-[#fff6ef] py-10"><PhoneFrame /></div>
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{features.map(([Icon,title,body]) => <article key={title} className="rounded-2xl border border-stone-200 bg-white p-5"><Icon className="h-5 w-5 text-[#007f7a]"/><h2 className="mt-4 font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-stone-600">{body}</p></article>)}</div>
    </div>

    <section className="mt-16">
      <div className="grid gap-7 lg:grid-cols-[.75fr_1.25fr] lg:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#007f7a]">How the ecosystem connects</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.04em]">One conversation. The right insight in the right place.</h2></div><p className="text-sm leading-7 text-stone-600">Tellie keeps the elder’s experience conversational and simple. Behind it, relevant information is structured differently for each authorised audience.</p></div>
      <div className="mt-8 grid gap-3 rounded-[28px] border border-stone-200 bg-white p-5 md:grid-cols-[1fr_auto_1fr_auto_1fr] md:items-center sm:p-8">
        <div className="rounded-2xl bg-[#edf8f7] p-5 text-center"><Mic2 className="mx-auto h-6 w-6 text-[#007f7a]"/><h3 className="mt-3 font-semibold">The elder talks with Tellie</h3><p className="mt-2 text-xs leading-5 text-stone-600">Conversation, preferences, interests and emotional signals.</p></div><ChevronRight className="mx-auto h-5 w-5 rotate-90 text-stone-400 md:rotate-0"/>
        <div className="group relative rounded-2xl bg-[#fff5ed] p-5 text-center" tabIndex={0}><ShieldCheck className="mx-auto h-6 w-6 text-[#b15f35]"/><h3 className="mt-3 font-semibold">Tellie extracts what is relevant</h3><p className="mt-2 text-xs leading-5 text-stone-600">Memory matrix, signals and privacy rules organise useful context.</p><div role="tooltip" className="pointer-events-none absolute -top-28 left-1/2 z-20 hidden w-72 -translate-x-1/2 rounded-2xl bg-[#283c3a] p-4 text-left text-xs leading-5 text-white shadow-xl group-hover:block group-focus:block">Tellie’s intended design does not store full conversation transcripts for dashboard use. It extracts and stores only relevant, permissioned information based on its memory matrix and algorithms. Final retention and consent rules are confirmed before scaled delivery.</div></div><ChevronRight className="mx-auto h-5 w-5 rotate-90 text-stone-400 md:rotate-0"/>
        <div className="rounded-2xl bg-[#f4f1fa] p-5 text-center"><Users className="mx-auto h-6 w-6 text-[#72639a]"/><h3 className="mt-3 font-semibold">Each audience sees its own view</h3><p className="mt-2 text-xs leading-5 text-stone-600">Family, residential provider or council—never one generic dashboard.</p></div>
      </div>
    </section>

    <ProductDashboards councilSrc={councilSrc} residentialSrc={residentialSrc} />

    <section className="mt-16"><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#007f7a]">What’s coming</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.04em]">Preserve a life. Understand the whole person.</h2><div className="mt-8 grid gap-5 lg:grid-cols-3"><article className="rounded-3xl border border-stone-200 bg-white p-7"><BookOpen className="h-6 w-6 text-[#007f7a]"/><h3 className="mt-5 text-xl font-semibold">Life-story archive</h3><p className="mt-3 text-sm leading-7 text-stone-600">With permission, Tellie can help an older adult build the story of their life over time—memories, places, relationships and lessons that the family can preserve.</p></article><article className="rounded-3xl border border-stone-200 bg-white p-7"><Smartphone className="h-6 w-6 text-[#007f7a]"/><h3 className="mt-5 text-xl font-semibold">Phone health integration</h3><p className="mt-3 text-sm leading-7 text-stone-600">Permissioned health and activity data could add context to conversation-informed wellbeing signals without turning Tellie into a diagnostic product.</p></article><article className="rounded-3xl border border-stone-200 bg-white p-7"><Watch className="h-6 w-6 text-[#007f7a]"/><h3 className="mt-5 text-xl font-semibold">Wearable context</h3><p className="mt-3 text-sm leading-7 text-stone-600">Wearables may provide movement, sleep or activity context that can be cross-referenced carefully with Tellie’s own signals.</p></article></div></section>

    <HardwarePrototypeSection />

    <div className="mt-12"><Detail title="Complete product capability map" open fullWidth><div className="grid w-full gap-x-10 gap-y-3 sm:grid-cols-2 lg:grid-cols-3">{[
      ['Real-time voice calls','Current'],['Text conversations','Current'],['10+ language configuration','Current'],['Conversation memory','Current'],['Preference learning','Current'],['Personalised responses','Current'],['Calendar and reminders','Current'],['Cognitive memory games','Current'],['Light web search','Current'],['Community activity discovery','Current'],['Support-contact configuration','Current'],['Support-contact alerts','Current'],['Accessibility settings','Current'],['Subscription entitlements','Current'],['Institutional activation','Current'],['Hardware telephone','Working prototype'],['Residential insight dashboard','Developed · activation'],['Council community dashboard','Developed · activation'],['Dashboard analytics','Developed · activation'],['Family-member experience','In development'],['Pilot analytics and reporting','In development']
    ].map(([item,status])=><div key={item} className="flex items-center justify-between gap-3 border-b border-stone-100 py-2"><span>{item}</span><span className={`shrink-0 rounded-full px-2 py-1 text-[10px] font-semibold uppercase tracking-wide ${status === 'Current' ? 'bg-[#eaf5f4] text-[#075e5b]' : status.startsWith('Developed') ? 'bg-[#eef3fb] text-[#3d5f91]' : status === 'Working prototype' ? 'bg-[#eee8f6] text-[#65558a]' : 'bg-[#fff2e9] text-[#9a4d21]'}`}>{status}</span></div>)}</div></Detail>
      <Detail title="Current product boundary">
        <div className="rounded-2xl bg-[#edf8f7] p-5 sm:p-6"><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#007f7a]">What Tellie is today</p><h3 className="mt-2 text-xl font-semibold text-[#283c3a]">A conversational entertainment and digital-engagement app.</h3><p className="mt-2 max-w-3xl text-sm leading-6">Tellie provides companionship, conversation, games, discovery and practical connection. It can surface permissioned wellbeing signals, but it does not provide care or clinical judgement.</p></div>
        <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[[Stethoscope,'Not a medical or clinical service','Tellie does not diagnose, treat or make clinical decisions.'],[TriangleAlert,'Not an emergency service','Tellie cannot replace emergency response or urgent human intervention.'],[CircleOff,'Not a surveillance tool','Tellie is designed around consent and relevant signals—not continuous monitoring.']].map(([Icon,title,body])=>{const C=Icon as typeof Stethoscope;return <article key={title as string} className="rounded-2xl border border-stone-200 bg-white p-5"><span className="grid h-10 w-10 place-items-center rounded-full bg-[#fff2e9]"><C className="h-5 w-5 text-[#a8542c]"/></span><h3 className="mt-4 font-semibold text-stone-800">{title as string}</h3><p className="mt-2 text-xs leading-5 text-stone-600">{body as string}</p></article>})}</div>
        <p className="mt-4 text-xs leading-5">Future health or wearable integrations would require explicit permission, firm product boundaries, and separate legal and privacy review.</p>
      </Detail>
      <Detail title="Product demonstration"><p>The portal’s demonstration area is ready for Micaela’s captioned walkthrough. The core demo can later be complemented by residential, council and family-experience demonstrations.</p></Detail></div>
  </>;
}
